### ISSUE TITLE
Multiple commands produce Assets.car

### ISSUE THREAD

**Issue by kanimetov** [verifoneone/verifone-ecom-ios-sdk#1]
Hello We are getting following issue

error: Multiple commands produce '/Users/zhkanimetov/Library/Developer/Xcode/DerivedData/qem-epqkarryruoygxbclsgcbvbdmhok/Build/Products/Release-iphonesimulator/qem.app/Assets.car'

Environment we are using

Xcode : Version 13.3.1 (12B45b
<img width="1511" alt="Screen Shot 2022-07-22 at 21 00 09" src="https://user-images.githubusercontent.com/21011898/180467566-6cf14e3d-9dd1-417f-8ede-e80015132052.png">
)

**Comment by kanimetov** [comment]
I use MacBook M1

**Comment by craigchristenson** [comment]
Thank you for reporting this issue. I have not been able to reproduce it yet but during the investigation I did find that the podspec for this library was not including all of the resources which could cause an issue. This was fixed in the latest version 1.0.1. I will continue investigating this issue but in the meantime can you try running a `pod update` and see if the issue still occurs?

**Comment by craigchristenson** [comment]
I was able to replicate the issue. Can you try adding the `use_frameworks!` option to your Podfile?

**Comment by kanimetov** [comment]
Yes, tried it, it didn't help . Unfortunately we gave up the SDK for now because we only need the encryption (we use Verifone api) and I have not tried to fix this error further . Thanks  )
